const PYODIDE_INDEX="https://cdn.jsdelivr.net/pyodide/v314.0.7/full/";
let pyodidePromise=null;
let seismicWithPad=false;
const $=id=>document.getElementById(id);
const $$=s=>[...document.querySelectorAll(s)];

function status(id,message,isError=false){const el=$(id);if(!el)return;el.textContent=message;el.classList.toggle('error',isError)}
function numberInput(id,label){const text=$(id)?.value.trim()??'';if(text==='')throw new Error(`${label} is blank.`);const value=Number(text);if(!Number.isFinite(value))throw new Error(`${label} must be numeric.`);return value}

function addGridRow(tableId,values=[]){const table=$(tableId);if(!table)return;const cols=Number(table.dataset.cols||0);const tr=document.createElement('tr');for(let i=0;i<cols;i++){const td=document.createElement('td');td.contentEditable='true';td.spellcheck=false;td.textContent=values[i]??'';tr.appendChild(td)}table.tBodies[0].appendChild(tr)}
function resetGrid(tableId,count=10){const table=$(tableId);if(!table)return;table.tBodies[0].innerHTML='';for(let i=0;i<count;i++)addGridRow(tableId)}
function gridToTsv(tableId){const table=$(tableId);if(!table)return'';return[...table.tBodies[0].rows].map(row=>[...row.cells].map(cell=>cell.textContent.trim())).filter(row=>row.some(v=>v!=='')).map(row=>row.join('\t')).join('\n')}
function splitPastedLine(line,cols){let parts;if(line.includes('\t'))parts=line.split('\t');else if(line.includes(','))parts=line.split(',');else parts=line.trim().split(/\s+/);parts=parts.map(v=>v.trim().replace(/^"|"$/g,''));while(parts.length<cols)parts.push('');return parts.slice(0,cols)}
function fillGridFromText(tableId,text){const table=$(tableId);if(!table)return;const cols=Number(table.dataset.cols||0);const lines=text.replace(/\r\n/g,'\n').replace(/\r/g,'\n').split('\n').filter(line=>line.trim()!=='');const rows=lines.map(line=>splitPastedLine(line,cols));table.tBodies[0].innerHTML='';rows.forEach(row=>addGridRow(tableId,row));for(let i=rows.length;i<Math.max(rows.length+3,10);i++)addGridRow(tableId)}
async function pasteGrid(tableId){try{const text=await navigator.clipboard.readText();fillGridFromText(tableId,text)}catch(e){status(tableId.startsWith('seis-')?'seismic-status':'wind-status','Clipboard access was blocked. Click a cell and use Ctrl+V instead.',true)}}
function setupGrid(tableId){const table=$(tableId);if(!table)return;resetGrid(tableId,10);table.addEventListener('paste',e=>{const text=e.clipboardData?.getData('text/plain');if(!text)return;e.preventDefault();fillGridFromText(tableId,text)})}

async function fetchToFS(py,url,fsName){const r=await fetch(url);if(!r.ok)throw new Error(`Could not load ${url}`);py.FS.writeFile(`/home/pyodide/site/${fsName}`,await r.text())}
async function getPyodideRuntime(){if(pyodidePromise)return pyodidePromise;pyodidePromise=(async()=>{const py=await loadPyodide({indexURL:PYODIDE_INDEX});py.FS.mkdirTree('/home/pyodide/site');await Promise.all([fetchToFS(py,'python/seismic_core.py','seismic_core.py'),fetchToFS(py,'python/wind_core.py','wind_core.py')]);py.runPython(`\nimport sys\nif "/home/pyodide/site" not in sys.path: sys.path.insert(0,"/home/pyodide/site")\nimport seismic_core, wind_core\n`);return py})().catch(err=>{pyodidePromise=null;throw err});return pyodidePromise}

async function calculateSeismic(){try{status('seismic-status','Calculating…');const py=await getPyodideRuntime();py.globals.set('web_node_text',gridToTsv('seis-nodes-grid'));py.globals.set('web_reaction_text',gridToTsv('seis-reactions-grid'));py.globals.set('web_sa02',numberInput('seis-sa02','Sa(0.2)'));py.globals.set('web_ie',numberInput('seis-ie','IE'));py.globals.set('web_rd',numberInput('seis-rd','Rd'));py.globals.set('web_ro',numberInput('seis-ro','Ro'));py.globals.set('web_height',numberInput('seis-height','Height adjustment'));py.globals.set('web_with_pad',seismicWithPad);const json=py.runPython(`\nimport json,seismic_core\nnodes=seismic_core._parse_clipboard_table(web_node_text,4)\nreactions=seismic_core._parse_clipboard_table(web_reaction_text,8)\nr=seismic_core.calculate_seismic(nodes,reactions,sa02=web_sa02,ie=web_ie,rd=web_rd,ro=web_ro,height_adjustment=web_height,with_pad=web_with_pad)\njson.dumps(r)\n`);const r=JSON.parse(json);$('m-coeff').textContent=r.coefficient.toFixed(9);$('m-total').textContent=`${r.total_vertical.toFixed(3)} kN`;$('m-excluded').textContent=`${r.excluded_weight.toFixed(3)} kN`;$('m-effective').textContent=`${r.effective_weight.toFixed(3)} kN`;$('m-vmax').textContent=`${r.vmax.toFixed(3)} kN`;$('m-count').textContent=String(r.count);$('seis-fz').textContent=r.fz_lines.join('\n');$('seis-fx').textContent=r.fx_lines.join('\n');status('seismic-status',`Calculation complete · ${r.count} matched reaction nodes.`)}catch(e){status('seismic-status',e.message,true)}}

async function calculateWind(){try{status('wind-status','Calculating…');const py=await getPyodideRuntime();py.globals.set('web_w_nodes',gridToTsv('wind-nodes-grid'));py.globals.set('web_w_members',gridToTsv('wind-members-grid'));py.globals.set('web_w_sections',gridToTsv('wind-sections-grid'));py.globals.set('web_w_height',numberInput('wind-height','Height adjustment'));py.globals.set('web_w_q',numberInput('wind-q','q'));py.globals.set('web_w_cg',numberInput('wind-cg','Cg'));const json=py.runPython(`\nimport json,wind_core\nnodes=wind_core._parse_clipboard_table(web_w_nodes,4)\nmembers=wind_core._parse_clipboard_table(web_w_members,7)\nsections=wind_core._parse_clipboard_table(web_w_sections,10)\nmax_height,gz,gx=wind_core.calculate_wind_outputs(nodes,members,sections,web_w_height,web_w_q,web_w_cg)\njson.dumps({"max_height":max_height,"gz":gz,"gx":gx})\n`);const r=JSON.parse(json);$('wind-maxheight').textContent=`${r.max_height.toFixed(3)} m`;$('wind-gz').textContent=r.gz.join('\n');$('wind-gx').textContent=r.gx.join('\n');status('wind-status',`Calculation complete · ${r.gz.length} Z-direction groups · ${r.gx.length} X-direction groups.`)}catch(e){status('wind-status',e.message,true)}}

async function copyTarget(id,button){await navigator.clipboard.writeText($(id).textContent);const old=button.textContent;button.textContent='Copied';setTimeout(()=>button.textContent=old,1000)}

document.addEventListener('DOMContentLoaded',()=>{
['seis-nodes-grid','seis-reactions-grid','wind-nodes-grid','wind-members-grid','wind-sections-grid'].forEach(setupGrid);
$$('[data-grid-paste]').forEach(b=>b.addEventListener('click',()=>pasteGrid(b.dataset.gridPaste)));
$$('[data-grid-add]').forEach(b=>b.addEventListener('click',()=>addGridRow(b.dataset.gridAdd)));
$$('[data-grid-clear]').forEach(b=>b.addEventListener('click',()=>resetGrid(b.dataset.gridClear,10)));
$$('[data-seismic-mode]').forEach(b=>b.addEventListener('click',()=>{seismicWithPad=b.dataset.seismicMode==='true';$$('[data-seismic-mode]').forEach(x=>x.classList.toggle('active',x===b));status('seismic-status',`Mode: ${seismicWithPad?'With pad':'No pad'}`)}));
$('seismic-calc')?.addEventListener('click',calculateSeismic);$('wind-calc')?.addEventListener('click',calculateWind);
$$('[data-copy-target]').forEach(b=>b.addEventListener('click',()=>copyTarget(b.dataset.copyTarget,b)));
});